CREATE TABLE IF NOT EXISTS SHY_PLAYER
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHAR(36) UNIQUE NOT NULL,
  name VARCHAR(16) NOT NULL,
  CONSTRAINT unique_uuid_cs UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS SHY_PARTICLE_EFFECT
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(32) NOT NULL,
  amount INTEGER,
  speed REAL,
  x REAL,
  y REAL,
  z REAL,
  material VARCHAR(32),
  data CHAR(4)
);

CREATE TABLE IF NOT EXISTS SHY_SKIN
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  typename VARCHAR(32),
  owner TEXT,
  datavalue INTEGER,
  unbreakable INTEGER
);

CREATE TABLE IF NOT EXISTS SHY_PET_MODIFIER
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  climbingheight REAL,
  movementspeed REAL
);

CREATE TABLE IF NOT EXISTS SHY_PET
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shy_player_id REFERENCES SHY_PLAYER(id),
  shy_skin_id REFERENCES SHY_SKIN(id),
  shy_modifier_id REFERENCES SHY_PET_MODIFIER(id),
  invincible INTEGER,
  health REAL,
  enabled INTEGER,
  displayname VARCHAR(32) NOT NULL,
  hitboxentitytype VARCHAR(32) NOT NULL,
  soundenabled INTEGER,
  particleenabled INTEGER,
  CONSTRAINT foreignkey_modifier_id_cs FOREIGN KEY (shy_modifier_id) REFERENCES SHY_PET_MODIFIER(id),
  CONSTRAINT foreignkey_player_id_cs FOREIGN KEY (shy_player_id) REFERENCES SHY_PLAYER(id),
  CONSTRAINT foreignkey_skin_id_cs FOREIGN KEY (shy_skin_id) REFERENCES SHY_SKIN(id)
)



