rootProject.name = "petblocks-root"

include("petblocks-api")
include("petblocks-bukkit-api")
include("petblocks-bukkit-plugin")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-108R3")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-109R2")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-110R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-111R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-112R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-113R2")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-114R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-115R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-116R3")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-117R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-118R1")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-118R2")
include("petblocks-bukkit-plugin:petblocks-bukkit-nms-119R1")
include("petblocks-core")
include("petblocks-sponge-api")
include("petblocks-sponge-plugin")
include("petblocks-tools")
include("petblocks-sponge-api")
