#######################################################################
#                          PetBlocks                                 #
# 		            	   by Shynixn							      #
#######################################################################

############################
# Language settings
############################
language: "en_us"

############################
# Command settings
############################
commands:
  petblocks:
    aliases:
      - "pet"
      - "pets"
  petblocksgui:
    aliases:
      - "petmenu"
      - "petgui"

############################
# Script Engine
############################
scriptEngine:
  # Option parameters for the NashornScriptEngine.
  options:
    - "--no-java-access=true"
    - "--persistent-code-cache=true"

############################
# Database
############################
database:
  # The pet data of a player is automatically saved when the player quits. You can additionally configure a saving interval for all cached pet data.
  autoSaveIntervalMinutes: 5
  # An artificial delay for read requests to the database in milliseconds. This can be used in server networks where multiple servers share the same pet database.
  # If the pet data is not in sync when switching between servers, try increasing this delay in steps e.g. 50, 100, 250, 500, 1000.
  readDelayMs: 0
  # The type of database to use. Possible values: sqlite, mysql
  type: "sqlite"
  # The JDBC properties are only used for type 'mysql'
  jdbc:
    # Replace localhost with your server name, 3306 with your port, PetBlocks with your database name.
    url: "jdbc:mysql://localhost:3306/PetBlocks"
    # Username of your database.
    username: ""
    # Password of your database.
    password: ""
    # Additional database properties. PetBlocks uses HikariCP (https://github.com/brettwooldridge/HikariCP) to cache SQL connections.
    # You may want to customize these depending on the size of your player base and your database performance.
    properties:
      - "useSSL=true"
      - "maximumPoolSize=5"
      - "cachePrepStmts=true"
      - "prepStmtCacheSize=250"
      - "prepStmtCacheSqlLimit=2048"

############################
# ThirdParty
############################
# When executing the /petblocks openheaddatabase command, this command is executed.
headDatabaseCommand: "/hdb"

############################
# Global pet settings
# For individual pet settings, use the files in the pets folder.
############################
pet:
  # A list of pets the player receives when joining the server. This list may be empty.
  receivePetsOnJoin:
    - name: "pet"
      template: "classic"
  # Render distance of the pet. They become invisible for players outside that range.
  renderDistance: 70
  # Displays a virtual trail of gold blocks, which represents the calculated path of the pet. Can be used for investigating pet paths. Rejoining the server removes the client side blocks.
  showPathfinder: false
  # Amount of milliseconds until the pet registers a new click on it.
  clickCoolDownMs: 70
  # A pathfinder run of a pet starts with a cube snapshot of the world, where a A* pathfinder implementation is applied after wards.
  # This setting defines how big of an area this cube should be. A larger cube requires more processing time and memory consumption.
  # Using a large cube is not recommend, as the pet should teleport or stay at its place when the owner is too far away.
  pathFinderCube:
    x: 28.0
    y: 10.0
    z: 28.0
  # The max amount of blocks, the pet accepts move to orders.
  pathFinderDistance: 20.0
  # Amount of milliseconds between updating the server position of the rider.
  # This value may be adjusted concerning your server ping and Anti Cheat Plugins.
  ridePositionUpdateMs: 250
  name:
    # Allows only certain letters as regex validation. (letters, numbers, underline, single quote, hashtag).
    # Be careful what you allow here, certain pet actions may break (scriptinjection) if you allow special characters.
    regex: "[0-9a-zA-Z_&'\\s#]*"
    minLength: 1
    maxLength: 20
    blacklist: # All values which are not allowed inside pet names. You probably need to add a lot of more swear words here for production servers.
      - "fuck"
      - "ass"
