name: PetBlocks
version: 9.25.0
author: Shynixn
main: com.github.shynixn.petblocks.PetBlocksPlugin
softdepend: [ PlaceholderAPI, HeadDatabase]
api-version: 1.13
libraries:
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.22.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.22.0
  - com.github.shynixn.mccoroutine:mccoroutine-folia-api:2.22.0
  - com.github.shynixn.mccoroutine:mccoroutine-folia-core:2.22.0
  - com.github.shynixn:fasterxml:1.2.0
  - com.zaxxer:HikariCP:5.1.0
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.25
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3
  - org.openjdk.nashorn:nashorn-core:15.4
