CREATE TABLE IF NOT EXISTS SHY_PLAYER
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  uuid CHAR(36),
  name VARCHAR(16),
  CONSTRAINT unique_uuid_cs UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS SHY_PETBLOCK
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  shy_player_id REFERENCES SHY_PLAYER(id),
  name VARCHAR(32)
);