CREATE TABLE IF NOT EXISTS SHY_PLAYER
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  uuid CHAR(36),
  name VARCHAR(16),
  CONSTRAINT unique_uuid_cs UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS SHY_PETBLOCK
(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shy_player_id REFERENCES SHY_PLAYER(id),
  name VARCHAR(32),
  CONSTRAINT foreignkey_player_id_cs FOREIGN KEY (shy_player_id) REFERENCES SHY_PLAYER(id)
);