CREATE TABLE IF NOT EXISTS SHY_PLAYER
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  uuid CHAR(36) UNIQUE NOT NULL,
  name VARCHAR(16) NOT NULL,
  CONSTRAINT unique_uuid_cs UNIQUE (uuid)
);

CREATE TABLE IF NOT EXISTS SHY_PARTICLE_EFFECT
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(32) NOT NULL,
  amount INTEGER,
  speed DOUBLE,
  x DOUBLE,
  y DOUBLE,
  z DOUBLE,
  material VARCHAR(32),
  data CHAR(4)
);

CREATE TABLE IF NOT EXISTS SHY_PETBLOCK
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  shy_player_id INTEGER,
  shy_particle_effect_id INTEGER,
  name VARCHAR(32) NOT NULL,
  engine INTEGER,
  material VARCHAR(32),
  data CHAR(4),
  skull TEXT,
  enabled INTEGER,
  age INTEGER,
  unbreakable INTEGER,
  play_sounds INTEGER,
  FOREIGN KEY (shy_player_id) REFERENCES SHY_PLAYER(id),
  FOREIGN KEY (shy_particle_effect_id) REFERENCES SHY_PARTICLE_EFFECT(id)
)