ALTER TABLE SHY_PETBLOCK ADD COLUMN engine INTEGER;
ALTER TABLE SHY_PETBLOCK DROP COLUMN SHY_PETBLOCK.TYPE;
ALTER TABLE SHY_PETBLOCK DROP COLUMN SHY_PETBLOCK.MOVING_TYPE;
ALTER TABLE SHY_PETBLOCK DROP COLUMN SHY_PETBLOCK.MOVEMENT_TYPE;