name: PetBlocks
version: 8.33.0
author: Shynixn
main: com.github.shynixn.petblocks.bukkit.PetBlocksPlugin
softdepend: [PlaceholderAPI, HeadDatabase]
commands:
  petblocks:
    description: Command to configure pets.
    useage: /<command>
    permission: petblocks.admin.command.pets
    permission-message: You don't have permission.
  petblockreload:
    description: Reloads the petblock config and lang file.
    usage: /<command>
    permission: petblocks.admin.command.reload
    permission-message: You don't have permission.
